[package]
name = "qsv2flv"
version = "0.1.1"
authors = ["ZhangZhilin <corex_public@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "~0.4"
clap = "~2.27.0"
